version: "2"

services:  
  redis:
    image: redis
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  worker:
    build: worker
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

